### ISSUE TITLE
Pytket 0.4.1 vs 0.5

### ISSUE THREAD

**Issue by johnzl-777** [CQCL/tket_benchmarking#1]
I understand the bulk of existing code is designed to work with pytket 0.4.1 but trying to get it to play nice with 0.5 brings up some problems I don't think the README addresses.

It seems like out of the box the `bench.py` file has certain import problems.

For example the first error I'm struck with is:
```python
Traceback (most recent call last):
  File "bench.py", line 129, in <module>
    tketpass = FullPeepholeOptimise()
NameError: name 'FullPeepholeOptimise' is not defined
```

If I fix that error by directly importing from `pytket.passes` there are still a number of functions that need more explicit import statements for Python to be happy. 

[The following modifications](https://github.com/Quantum-Computing-at-Davis/tket_benchmarking/blob/257ff2848c8a40a4d5c49018c9e69f68cd1ddd3c/bench.py#L2) I've made to the imports seem to allow things to run properly.

Furthermore, there are some functions I wasn't able to find in the latest documentation such as `gen_decompose_routing_gates_to_cxs_pass()` which I substituted with the [closest equivalents I could see in 0.5](https://github.com/Quantum-Computing-at-Davis/tket_benchmarking/blob/257ff2848c8a40a4d5c49018c9e69f68cd1ddd3c/bench.py#L213)

The documentation doesn't state the need to make any explicit code changes for the benchmark code to work between 0.4.1 and 0.5. Only that using 0.5 provides newer (and faster) circuit analysis functions.

Would it be possible to have this mentioned in the README.md or have separate `bench.py`'s to account for this?

**Comment by willsimmons1465** [comment]
Thank you very much for flagging this up. We were planning on separating out an "active" benchmarking script from the one used for https://arxiv.org/abs/2003.10611 to try and support ongoing benchmarks. I have now updated the repository structure to reflect this and hopefully be a little easier to maintain in the future.

The paper version of the script can now successfully run the pytket benchmarks with pytket v0.4.1 and for the other systems with pytket v0.5.2. The active version of the script has been updated to work with pytket v0.5.4 only for all tests. We hope to push a complete set of data for the up-to-date benchmarks soon.

If you have any further opinions on how we could improve our active benchmarks or continue to have difficulty with running them, please reopen this issue and let us know.
